
name: CI 

on: 
  
  push: 
    branches: [ "main" ]

  pull_request: 
    branches: [ "main" ]


jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: build image 
        run: docker build -t simbadock82/portfolio .

      
      - name: push image
        run: |
          docker login -u simbadock82 -p ${{secrets.REGISTRY_PASS}} 
          docker push simbadock82/portfolio
